using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("DayZ Commander")]
[assembly: AssemblyCompanyAttribute("Dotjosh Open Source")]
[assembly: AssemblyProductAttribute("DayZ Commander")]
[assembly: AssemblyCopyrightAttribute("Copyright 2012")]
[assembly: AssemblyVersionAttribute("0.9.0.34")]
[assembly: AssemblyFileVersionAttribute("0.9.0.34")]

